version: "3.8"

networks:
    shared-services:
        driver: bridge
        name: shared-services

services:
  jarvis:
    restart: always
    build:
      context: .
      target: dev
    volumes:
      - ".:/application"
    ports:
      - 8085:8085
    networks:
      - shared-services
