from .settings import MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD
from .settings import MYSQL_HOSTNAME, MYSQL_PORT, APP_HOST, APP_PORT
from .settings import AWS_REGION_NAME, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, USER, PASSWORD