import os

MYSQL_DATABASE = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("MYSQL_DATABASE")
MYSQL_USER = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("MYSQL_USER")
MYSQL_PASSWORD = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("MYSQL_PASSWORD")
MYSQL_HOSTNAME = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("MYSQL_HOSTNAME")
MYSQL_PORT = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("MYSQL_PORT")
APP_HOST = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("APP_HOST")
AWS_REGION_NAME = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("AWS_REGION_NAME")
AWS_ACCESS_KEY_ID = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("AWS_SECRET_ACCESS_KEY")