import os

MYSQL_DATABASE = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("MYSQL_DATABASE")
MYSQL_USER = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("MYSQL_USER")
MYSQL_PASSWORD = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("MYSQL_PASSWORD")
MYSQL_HOSTNAME = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("MYSQL_HOSTNAME")
MYSQL_PORT = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("MYSQL_PORT")
APP_HOST = os.enviMYSQL_ROOT_PASSWORD = os.environ.get("APP_HOST")